# Generated by Django 4.2.7 on 2024-09-16 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, choices=[('Supermarket', 'Supermarket'), ('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Bar', 'Bar'), ('WholeSale', 'WholeSale'), ('Ice Cream', 'Ice Cream')], default='', max_length=500, null=True, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='ManagementLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_level', models.CharField(blank=True, choices=[('Management', 'Management'), ('Employee', 'Employee')], default='', max_length=500, null=True, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Management Level',
                'verbose_name_plural': 'Management Level',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_department_name', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie'), ('Patisserie', 'Patisserie'), ('Magazine', 'Magazine')], default='', max_length=500, null=True, verbose_name='Sub Department')),
                ('department_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.department', verbose_name='Dapartment')),
            ],
            options={
                'verbose_name': 'Sub Department',
                'verbose_name_plural': 'Sub Departments',
            },
        ),
    ]
