# Generated by Django 4.2.7 on 2024-09-16 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_type', models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Sole Proprietor', 'Sole Proprietor'), ('Customer', 'Customer'), ('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual'), ('School', 'School'), ('NGOs', 'NGOs')], max_length=100, null=True, verbose_name='Customer Type')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Company Name')),
                ('company_box', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Own Company Box')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area')),
                ('quarter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quarter')),
                ('street', models.CharField(blank=True, choices=[('Along the Road', 'Along the Road'), ('Inside the Street', 'Inside the Street')], max_length=300, null=True, verbose_name='Street')),
                ('street_location', models.CharField(blank=True, choices=[('Along the Road', 'Along the Road'), ('Inside the Street', 'Inside the Street')], max_length=30, null=True, verbose_name='Own Company Box')),
                ('address', models.TextField(max_length=2550, null=True, verbose_name='Address')),
                ('city', models.CharField(default='Kumba', max_length=100, verbose_name='City')),
                ('region', models.CharField(default='South West Region', max_length=200, verbose_name='Region')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone +237')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
