# Generated by Django 4.2.3 on 2024-07-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100, unique=True, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Selling Price Pos')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('entry_weight_per_boule', models.CharField(default='', max_length=100, verbose_name='Entry Weight/Boule')),
                ('weight_per_boule_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Weight/Boule/kg')),
                ('weight_per_boule_gram', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Weight/Boule/grams')),
                ('output_per_boule', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Output/Boule')),
                ('unit_output_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Weight/Unit Output/grams')),
                ('category', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.department'),
        ),
    ]
