# Generated by Django 5.0.7 on 2024-09-19 03:52

import boulangerie.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoulangerieCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Defualt Customer', max_length=200, unique=True, verbose_name='Customer Name')),
                ('customer_type', models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Sole Proprietor', 'Sole Proprietor'), ('Customer', 'Customer'), ('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual'), ('School', 'School'), ('NGOs', 'NGOs')], max_length=100, null=True, verbose_name='Customer Type')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Company Name')),
                ('company_box', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Own Company Box')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area')),
                ('quarter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quarter')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street')),
                ('street_location', models.CharField(blank=True, choices=[('Along the Road', 'Along the Road'), ('Inside the Street', 'Inside the Street')], max_length=30, null=True, verbose_name='Street Location')),
                ('address', models.TextField(max_length=2550, null=True, verbose_name='Address')),
                ('city', models.CharField(default='Kumba', max_length=100, verbose_name='City')),
                ('region', models.CharField(default='South West Region', max_length=200, verbose_name='Region')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone +237')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Boulangerie Customer',
                'verbose_name_plural': 'Boulangerie Customers',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('inventory_id', models.CharField(blank=True, default=boulangerie.models.increment_inventory_number, max_length=500, null=True, verbose_name='Inventory Id')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Stock Person')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=20, null=True, verbose_name='Total Price')),
            ],
            options={
                'verbose_name': 'Boulangerie Inventory',
                'verbose_name_plural': 'Boulangerie Inventory',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100, unique=True, verbose_name='Product Name')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Barcode')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Selling Price')),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Reorder Level')),
            ],
            options={
                'verbose_name': 'Boulangerie Product',
                'verbose_name_plural': 'Boulangerie Products',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(default='', max_length=100, verbose_name='Sub Category Name')),
            ],
            options={
                'verbose_name': 'Boulangerie Product Sub Category',
                'verbose_name_plural': 'Boulangerie Product Sub Category',
            },
        ),
        migrations.CreateModel(
            name='BoulangeriePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('purchase_id', models.CharField(blank=True, default=boulangerie.models.increment_purchase_number, max_length=500, null=True, verbose_name='Customer Name')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('status', models.CharField(blank=True, choices=[('Purchases', 'Purchases'), ('Return Outwards', 'Return Outwards')], default='Purchases', max_length=500, null=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('purchase_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Purchase Total')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Net Amount')),
            ],
            options={
                'verbose_name': 'Boulangerie Purchase Invoice',
                'verbose_name_plural': 'Boulangerie Purchase Invoice',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('supplier_type', models.CharField(blank=True, choices=[('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual')], max_length=100, null=True, verbose_name='Supplier Type')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Company Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('address', models.TextField(blank=True, max_length=2550, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, default='Kumba', max_length=100, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, default='South West Region', max_length=200, null=True, verbose_name='Region')),
                ('phone1', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone 1 +237')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone 2 +237')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': ' Boulangerie Suppliers',
                'verbose_name_plural': 'Boulangerie Suppliers',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('invoice_id', models.CharField(blank=True, default=boulangerie.models.Boulangerie_increment_invoice_number, max_length=500, null=True, verbose_name='Invoice Id')),
                ('status', models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Return Inwards', 'Return Inwards')], default='Morning', max_length=500, null=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Invoice Total')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangeriecustomer', verbose_name='Customer Name')),
            ],
            options={
                'verbose_name': 'Boulangerie Customer Invoice',
                'verbose_name_plural': 'Boulangerie Customer Invoice',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_installment', models.CharField(blank=True, choices=[('1st Installment', '1st Installment'), ('2nd Installment', '2nd Installment'), ('3rd Installment', '3rd Installment'), ('4th Installment', '4th Installment'), ('5th Installment', '5th Installment'), ('6th Installment', '6th Installment'), ('7th Installment', '7th Installment'), ('8th Installment', '8th Installment'), ('9th Installment', '9th Installment'), ('10th Installment', '10th Installment')], default='1st Installment', max_length=500, null=True)),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangeriecustomer', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangerieinvoice')),
            ],
            options={
                'verbose_name': 'Boulangerie Customers Payments',
                'verbose_name_plural': 'Boulangerie Customers Payments',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangeriecustomer', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangerieinvoice', verbose_name='Invoice Id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangerieproduct', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Customers Opening Balance',
                'verbose_name_plural': 'Customers Opening Balance',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(default='', max_length=200, verbose_name='Sale Person')),
                ('delivery_man', models.CharField(default='', max_length=200, verbose_name='Delivery Man')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('unit_cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('unit_selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total_cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total_selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('discount_price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('discount_value', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangerieinvoice', verbose_name='Invoice Id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangerieproduct', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Boulangerie Customer InvoicedItems',
                'verbose_name_plural': 'Boulangerie Customer InvoicedItems',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieInventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Added Stock', 'Added Stock'), ('Closing Stock', 'Closing Stock'), ('Damages', 'Damages'), ('Returns Outwards', 'Returns Outwards'), ('Returns Inwards', 'Returns Inwards')], default='Morning', max_length=500, null=True)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Selling Price')),
                ('total_cost_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Total Cost Price')),
                ('total_selling_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Total Selling Price')),
                ('inventory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangerieinventory', verbose_name='Inventory Id')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangerieproduct', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Boulangerie Inventory Item',
                'verbose_name_plural': 'Boulangerie Inventory Items',
            },
        ),
        migrations.AddField(
            model_name='boulangerieproduct',
            name='sub_category_name',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangerieproductsubcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='BoulangeriePurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Discount price')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Discount Amount')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_purchase', to='boulangerie.boulangerieproduct', verbose_name='Product Name')),
                ('purchase_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangeriepurchase', verbose_name='Purchase Id')),
            ],
            options={
                'verbose_name': 'Boulangerie Purchase Item',
                'verbose_name_plural': 'Boulangerie Purchase Items',
            },
        ),
        migrations.CreateModel(
            name='BoulangeriePurchaseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('purchase_id', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Purchase ID')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Purchase Value')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Amount Paid')),
                ('balance_due', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Balance Due')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('supplier_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangeriesupplier', verbose_name="Supplier's Name")),
            ],
            options={
                'verbose_name': 'Boulangerie Purchase Summary',
                'verbose_name_plural': 'Boulangerie Purchase Summary',
            },
        ),
        migrations.AddField(
            model_name='boulangeriepurchase',
            name='supplier_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boulangerie.boulangeriesupplier', verbose_name="Supplier's Name"),
        ),
    ]
