# Generated by Django 4.2.7 on 2024-09-16 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import production.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('inventory', '0001_initial'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('production_id', models.CharField(blank=True, default=production.models.increment_production_number, max_length=500, null=True)),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Session')),
                ('supervisor', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Supervisor')),
                ('sub_department', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.subdepartment', verbose_name='Sub Department')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Production',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mixture_number', models.CharField(blank=True, choices=[('First Mixture', 'First Mixture'), ('Second Mixture', 'Second Mixture'), ('Third Mixture', 'Third Mixture'), ('Fourth Mixture', 'Fourth Mixture'), ('Fifth Mixture', 'Fifth Mixture'), ('Sixth Mixture', 'Sixth Mixture'), ('Seventh Mixture', 'Seventh Mixture'), ('Eighth Mixture', 'Eighth Mixture'), ('Ninth Mixture', 'Ninth Mixture'), ('Tenth Mixture', 'Tenth Mixture'), ('Eleventh Mixture', 'Eleventh Mixture'), ('Twelfth Mixture', 'Twelfth Mixture'), ('Thirteenth Mixture', 'Thirteenth Mixture'), ('Fourteenth Mixture', 'Fourteenth Mixture'), ('Fifteenth Mixture', 'Fifteenth Mixture'), ('Sixteenth Mixture', 'Sixteenth Mixture'), ('Seventeenth Mixture', 'Seventeenth Mixture'), ('Eighteenth Mixture', 'Eighteenth Mixture'), ('Ninteenth Mixture', 'Nineteenth Mixture'), ('Twentieth Mixture', 'Twentieth Mixture'), ('Twenty First Mixture', 'Twenty First Mixture'), ('Twenty Second Mixture', 'Twenty Second Mixture'), ('Twenty Third Mixture', 'Twenty Third Mixture')], default='', max_length=500, null=True, verbose_name='Mixture Number')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Quantity Used')),
                ('rm_total_weight_grams', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='RM Total Weight (Grams)')),
                ('unit_cost_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Unit Cost Price')),
                ('raw_material_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Raw Material Value')),
                ('production_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.production')),
                ('raw_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rawmaterials', verbose_name='Raw Material')),
            ],
            options={
                'verbose_name': 'Raw Material Usage',
                'verbose_name_plural': 'Raw Material Usage',
            },
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_category', models.CharField(blank=True, choices=[('Finished', 'Finished'), ('SemiFinished', 'SemiFinished')], default='Finished', max_length=500, null=True, verbose_name='Output Category')),
                ('mixture_number', models.CharField(blank=True, choices=[('First Mixture', 'First Mixture'), ('Second Mixture', 'Second Mixture'), ('Third Mixture', 'Third Mixture'), ('Fourth Mixture', 'Fourth Mixture'), ('Fifth Mixture', 'Fifth Mixture'), ('Sixth Mixture', 'Sixth Mixture'), ('Seventh Mixture', 'Seventh Mixture'), ('Eighth Mixture', 'Eighth Mixture'), ('Ninth Mixture', 'Ninth Mixture'), ('Tenth Mixture', 'Tenth Mixture'), ('Eleventh Mixture', 'Eleventh Mixture'), ('Twelfth Mixture', 'Twelfth Mixture'), ('Thirteenth Mixture', 'Thirteenth Mixture'), ('Fourteenth Mixture', 'Fourteenth Mixture'), ('Fifteenth Mixture', 'Fifteenth Mixture'), ('Sixteenth Mixture', 'Sixteenth Mixture'), ('Seventeenth Mixture', 'Seventeenth Mixture'), ('Eighteenth Mixture', 'Eighteenth Mixture'), ('Ninteenth Mixture', 'Nineteenth Mixture'), ('Twentieth Mixture', 'Twentieth Mixture'), ('Twenty First Mixture', 'Twenty First Mixture'), ('Twenty Second Mixture', 'Twenty Second Mixture'), ('Twenty Third Mixture', 'Twenty Third Mixture')], default='', max_length=500, null=True, verbose_name='Mixture Number')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Quantity')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Price')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Output Value')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('production_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.production')),
            ],
            options={
                'verbose_name': 'Production Output',
                'verbose_name_plural': 'Production Output',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionDamages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Consumption', 'Consumption'), ('Damages', 'Damages'), ('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], default='', max_length=500, null=True, verbose_name='Status')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Quantity')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Price')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Output Value')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('production_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.production')),
            ],
            options={
                'verbose_name': 'Consumption & Damages',
                'verbose_name_plural': 'Consumption & Damages',
            },
        ),
    ]
