# Generated by Django 4.2.7 on 2024-08-29 06:46

from django.db import migrations, models
import purchases.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0102_alter_invoices_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_id',
            field=models.CharField(blank=True, default=purchases.models.increment_invoice_number, max_length=500, null=True, verbose_name='Purchase Invoice Id'),
        ),
    ]
