# Generated by Django 4.2.7 on 2024-09-26 06:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import supermarket.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupermarketCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, unique=True, verbose_name='Customer Name')),
                ('customer_type', models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Sole Proprietor', 'Sole Proprietor'), ('Customer', 'Customer'), ('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual'), ('School', 'School'), ('NGOs', 'NGOs')], max_length=100, null=True, verbose_name='Customer Type')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Company Name')),
                ('company_box', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Own Company Box')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area')),
                ('quarter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quarter')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street')),
                ('street_location', models.CharField(blank=True, choices=[('Along the Road', 'Along the Road'), ('Inside the Street', 'Inside the Street')], max_length=30, null=True, verbose_name='Street Location')),
                ('address', models.TextField(max_length=2550, null=True, verbose_name='Address')),
                ('city', models.CharField(default='Kumba', max_length=100, verbose_name='City')),
                ('region', models.CharField(default='South West Region', max_length=200, verbose_name='Region')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone +237')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('account_photo', models.ImageField(default='/static/app-assets/images/portrait/small/avatar-s-19.png', max_length=255, upload_to=supermarket.models.SupermarketCustomer.upload_to)),
            ],
            options={
                'verbose_name': 'Supermarket Customer',
                'verbose_name_plural': 'Supermarket Customers',
            },
        ),
        migrations.CreateModel(
            name='SupermarketInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('inventory_id', models.CharField(blank=True, default=supermarket.models.increment_inventory_number, max_length=500, null=True, verbose_name='Inventory Id')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('department_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Supermarket Inventory',
                'verbose_name_plural': 'Supermarket Inventory',
            },
        ),
        migrations.CreateModel(
            name='SupermarketInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('invoice_id', models.CharField(blank=True, default=supermarket.models.supermarket_increment_invoice_number, max_length=500, null=True, verbose_name='Invoice Id')),
                ('sales_session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Wholeday', 'Wholeday')], default='Morning', max_length=500, null=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('sales_person', models.CharField(choices=[('Moses', 'Moses'), ('Nelson', 'Nelson')], default='', max_length=200, verbose_name='Sale Person')),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Invoice Total')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('apply_vat', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Return Inwards', 'Return Inwards')], max_length=500, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketcustomer', verbose_name='Customer Name')),
                ('department_name', models.ForeignKey(blank=True, default='Supermarket', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Supermarket Customer Invoice',
                'verbose_name_plural': 'Supermarket Customer Invoice',
            },
        ),
        migrations.CreateModel(
            name='SupermarketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100, unique=True, verbose_name='Product Name')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Barcode')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Selling Price')),
            ],
            options={
                'verbose_name': 'Supermarket Product',
                'verbose_name_plural': 'Supermarket Products',
            },
        ),
        migrations.CreateModel(
            name='SupermarketProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(default='', max_length=100, verbose_name='Sub Category Name')),
            ],
            options={
                'verbose_name': 'Supermarket Product Sub Category',
                'verbose_name_plural': 'Supermarket Product Sub Category',
            },
        ),
        migrations.CreateModel(
            name='SupermarketPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ordered Date')),
                ('recieved_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Recieved Date')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('purchase_id', models.CharField(blank=True, default=supermarket.models.increment_purchase_number, max_length=500, null=True, verbose_name='Customer Name')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('purchase_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Purchase Total')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='VAT Amount')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Discount Amount')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Net Amount')),
                ('department', models.ForeignKey(blank=True, default=supermarket.models.SupermarketPurchase.get_default_department, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Supermarket Purchase Invoice',
                'verbose_name_plural': 'Supermarket Purchase Invoice',
            },
        ),
        migrations.CreateModel(
            name='SupermarketSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('supplier_type', models.CharField(blank=True, choices=[('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual')], max_length=100, null=True, verbose_name='Supplier Type')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Company Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('address', models.TextField(blank=True, max_length=2550, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, default='Kumba', max_length=100, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, default='South West Region', max_length=200, null=True, verbose_name='Region')),
                ('phone1', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone 1 +237')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone 2 +237')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': ' Supermarket Suppliers',
                'verbose_name_plural': 'Supermarket Suppliers',
            },
        ),
        migrations.CreateModel(
            name='SupermarketReturnsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketcustomer', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketinvoice', verbose_name='Invoice Id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketproduct', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Customers Return Item',
                'verbose_name_plural': 'Customers Return Items',
            },
        ),
        migrations.CreateModel(
            name='SupermarketPurchaseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('purchase_id', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Purchase ID')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Purchase Value')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Amount Paid')),
                ('balance_due', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Balance Due')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('supplier_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketsupplier', verbose_name="Supplier's Name")),
            ],
            options={
                'verbose_name': 'Supermarket Purchase Summary',
                'verbose_name_plural': 'Supermarket Purchase Summary',
            },
        ),
        migrations.CreateModel(
            name='SupermarketPurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_installment', models.CharField(blank=True, choices=[('1st Installment', '1st Installment'), ('2nd Installment', '2nd Installment'), ('3rd Installment', '3rd Installment'), ('4th Installment', '4th Installment'), ('5th Installment', '5th Installment'), ('6th Installment', '6th Installment'), ('7th Installment', '7th Installment'), ('8th Installment', '8th Installment'), ('9th Installment', '9th Installment'), ('10th Installment', '10th Installment')], default='1st Installment', max_length=500, null=True)),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('payment_id', models.CharField(blank=True, default=supermarket.models.increment_invoice_number, max_length=500, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketcustomer', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketinvoice')),
            ],
            options={
                'verbose_name': 'Supermarket Purchase Payments',
                'verbose_name_plural': 'Supermarket Purchase Payments',
            },
        ),
        migrations.CreateModel(
            name='SupermarketPurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('ordered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ordered Date')),
                ('recieved_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Recieved Date')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('unit_cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('unit_selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total_cost_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('total_selling_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Discount value')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Discount Amount')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Net Amount')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_purchase', to='supermarket.supermarketproduct', verbose_name='Product Name')),
                ('purchase_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketpurchase', verbose_name='Purchase Id')),
            ],
            options={
                'verbose_name': 'Supermarket Purchase Item',
                'verbose_name_plural': 'Supermarket Purchase Items',
            },
        ),
        migrations.AddField(
            model_name='supermarketpurchase',
            name='supplier_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketsupplier', verbose_name="Supplier's Name"),
        ),
        migrations.CreateModel(
            name='SupermarketProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('production_id', models.CharField(blank=True, default=supermarket.models.increment_production_number, max_length=500, null=True)),
                ('department', models.CharField(blank=True, choices=[('Supermarket', 'Supermarket')], default='Supermarket', max_length=500, null=True, verbose_name='Department')),
                ('session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Session')),
                ('supervisor', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Supervisor')),
                ('sub_department', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.subdepartment', verbose_name='Sub Department')),
            ],
            options={
                'verbose_name': 'Supermarket Production',
                'verbose_name_plural': 'Supermarket Production',
            },
        ),
        migrations.CreateModel(
            name='SupermarketProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100, verbose_name='Category Name')),
                ('sub_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.subdepartment', verbose_name='Sub Department')),
            ],
            options={
                'verbose_name': 'Supermarket Product Category',
                'verbose_name_plural': 'Supermarket Product Category',
            },
        ),
        migrations.AddField(
            model_name='supermarketproduct',
            name='sub_category_name',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketproductsubcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='SupermarketInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_id', models.CharField(blank=True, default=supermarket.models.increment_invoice_number, max_length=500, null=True)),
                ('payment_installment', models.CharField(blank=True, choices=[('1st Installment', '1st Installment'), ('2nd Installment', '2nd Installment'), ('3rd Installment', '3rd Installment'), ('4th Installment', '4th Installment'), ('5th Installment', '5th Installment'), ('6th Installment', '6th Installment'), ('7th Installment', '7th Installment'), ('8th Installment', '8th Installment'), ('9th Installment', '9th Installment'), ('10th Installment', '10th Installment')], default='1st Installment', max_length=500, null=True)),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketcustomer', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketinvoice')),
            ],
            options={
                'verbose_name': 'Supermarket Customers Payments',
                'verbose_name_plural': 'Supermarket Customers Payments',
            },
        ),
        migrations.CreateModel(
            name='SupermarketInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('discount_price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('discount_value', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketinvoice', verbose_name='Invoice Id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketproduct', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Supermarket Customer InvoicedItems',
                'verbose_name_plural': 'Supermarket Customer InvoicedItems',
            },
        ),
        migrations.CreateModel(
            name='SupermarketInventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('status', models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], default='Morning', max_length=500, null=True)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('inventory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketinventory', verbose_name='Invoice Id')),
                ('raw_material_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketproduct', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Supermarket Inventory Item',
                'verbose_name_plural': 'Supermarket Inventory Items',
            },
        ),
        migrations.CreateModel(
            name='SupermarketCustomerOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, choices=[('Opening Balance', 'Opening Balance')], default='Customer Opening Balance', max_length=500, null=True, verbose_name='Description')),
                ('amount_owed', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketcustomer', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketinvoice')),
            ],
            options={
                'verbose_name': 'Supermarket Customer Opening Balance',
                'verbose_name_plural': 'Supermarket Customer Opening Balance',
            },
        ),
        migrations.CreateModel(
            name='SupermarketConsumptionDamages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Consumption', 'Consumption'), ('Damages', 'Damages')], default='', max_length=500, null=True, verbose_name='Status')),
                ('session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Session')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Employee')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Quantity')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Price')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Output Value')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketproduct')),
                ('production_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarketproduction')),
                ('sub_department', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.subdepartment', verbose_name='Sub Department')),
            ],
            options={
                'verbose_name': 'Supermarket Consumption & Damages',
                'verbose_name_plural': 'Supermarket Consumption & Damages',
            },
        ),
    ]
