# Generated by Django 4.2.7 on 2024-09-16 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('inventory_id', models.CharField(blank=True, default=inventory.models.increment_inventory_number, max_length=500, null=True, verbose_name='Inventory Id')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('sub_department', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.subdepartment', verbose_name='Sub Department')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Product Name')),
                ('category', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='Direct', max_length=500, null=True, verbose_name='Category')),
                ('weight_pack', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Weight/Pack')),
                ('entry_measure', models.CharField(choices=[('Grams', 'Grams'), ('Kg', 'Kg'), ('Unit', 'Unit'), ('Litre', 'Litre')], max_length=200, verbose_name='Entry Measure')),
                ('packaging', models.CharField(blank=True, choices=[('Bags', 'Bags'), ('Packets', 'Packets'), ('Bottle', 'Bottle'), ('Sachets', 'Sachets'), ('Buckets', 'Buckets'), ('Litre', 'Litre'), ('Trays', 'Trays'), ('Carton', 'Carton'), ('Container', 'Container')], default='', max_length=500, null=True, verbose_name='Packaging')),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Materials',
            },
        ),
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('status', models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Added Stock', 'Added Stock'), ('Transfer Inwards', 'Transfer Inwards'), ('Transfer Outwards', 'Transfer Outwards'), ('Closing Stock', 'Closing Stock')], default='Morning', max_length=500, null=True)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('inventory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory', verbose_name='Invoice Id')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rawmaterials', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
            },
        ),
    ]
