# Generated by Django 4.2.7 on 2024-09-26 06:02

import bakery.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_type', models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Sole Proprietor', 'Sole Proprietor'), ('Customer', 'Customer'), ('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual'), ('School', 'School'), ('NGOs', 'NGOs')], max_length=100, null=True, verbose_name='Customer Type')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Company Name')),
                ('company_box', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Own Company Box')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area')),
                ('quarter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quarter')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street')),
                ('street_location', models.CharField(blank=True, choices=[('Along the Road', 'Along the Road'), ('Inside the Street', 'Inside the Street')], max_length=30, null=True, verbose_name='Street Location')),
                ('address', models.TextField(max_length=2550, null=True, verbose_name='Address')),
                ('city', models.CharField(default='Kumba', max_length=100, verbose_name='City')),
                ('region', models.CharField(default='South West Region', max_length=200, verbose_name='Region')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone +237')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('account_photo', models.ImageField(default='/static/app-assets/images/portrait/small/avatar-s-19.png', max_length=255, upload_to=bakery.models.BakeryCustomer.upload_to)),
            ],
            options={
                'verbose_name': 'Bakery Customer',
                'verbose_name_plural': 'Bakery Customers',
            },
        ),
        migrations.CreateModel(
            name='BakeryInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('inventory_id', models.CharField(blank=True, default=bakery.models.increment_inventory_number, max_length=500, null=True, verbose_name='Inventory Id')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('department_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Bakery Inventory',
                'verbose_name_plural': 'Bakery Inventory',
            },
        ),
        migrations.CreateModel(
            name='BakeryInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(choices=[('Moses', 'Moses'), ('Nelson', 'Nelson')], default='', max_length=200, verbose_name='Sale Person')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('invoice_id', models.CharField(blank=True, default=bakery.models.bakery_increment_invoice_number, max_length=500, null=True, verbose_name='Invoice Id')),
                ('sales_session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='Morning', max_length=400, null=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Invoice Total')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('apply_vat', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Return Inwards', 'Return Inwards')], default='Sales', max_length=500, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakerycustomer', verbose_name='Customer Name')),
            ],
            options={
                'verbose_name': 'Bakery Customer Invoice',
                'verbose_name_plural': 'Bakery Customer Invoice',
            },
        ),
        migrations.CreateModel(
            name='BakeryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100, unique=True, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Supply Price')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Selling Price')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('entry_weight_per_boule', models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='Entry Weight/Boule')),
                ('weight_per_boule_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Weight/Boule/kg')),
                ('weight_per_boule_gram', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Weight/Boule/grams')),
                ('output_per_boule', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Output/Boule')),
                ('unit_output_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Weight/Unit Output/grams')),
            ],
            options={
                'verbose_name': 'Bakery Product',
                'verbose_name_plural': 'Bakery Products',
            },
        ),
        migrations.CreateModel(
            name='BakeryProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('production_id', models.CharField(blank=True, default=bakery.models.increment_production_number, max_length=500, null=True)),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('mixture_number', models.CharField(blank=True, choices=[('First Mixture', 'First Mixture'), ('Second Mixture', 'Second Mixture'), ('Third Mixture', 'Third Mixture'), ('Fourth Mixture', 'Fourth Mixture'), ('Fifth Mixture', 'Fifth Mixture'), ('Sixth Mixture', 'Sixth Mixture'), ('Seventh Mixture', 'Seventh Mixture'), ('Eighth Mixture', 'Eighth Mixture'), ('Ninth Mixture', 'Ninth Mixture'), ('Tenth Mixture', 'Tenth Mixture'), ('Eleventh Mixture', 'Eleventh Mixture'), ('Twelfth Mixture', 'Twelfth Mixture'), ('Thirteenth Mixture', 'Thirteenth Mixture'), ('Fourteenth Mixture', 'Fourteenth Mixture'), ('Fifteenth Mixture', 'Fifteenth Mixture'), ('Sixteenth Mixture', 'Sixteenth Mixture'), ('Seventeenth Mixture', 'Seventeenth Mixture'), ('Eighteenth Mixture', 'Eighteenth Mixture'), ('Ninteenth Mixture', 'Nineteenth Mixture'), ('Twentieth Mixture', 'Twentieth Mixture'), ('Twenty First Mixture', 'Twenty First Mixture'), ('Twenty Second Mixture', 'Twenty Second Mixture'), ('Twenty Third Mixture', 'Twenty Third Mixture')], default='', max_length=500, null=True, verbose_name='Mixture Number')),
                ('session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Session')),
                ('supervisor', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Supervisor')),
                ('stock_supervisor', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Stock Supervisor')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Total Cost Price')),
                ('sub_department', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.subdepartment', verbose_name='Sub Department')),
            ],
            options={
                'verbose_name': 'Bakery Production',
                'verbose_name_plural': 'Bakery Production',
            },
        ),
        migrations.CreateModel(
            name='BakeryPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, default='Bakery', max_length=100, null=True, verbose_name='Department')),
                ('ordered_date', models.DateTimeField(verbose_name='Order Data-Time')),
                ('recieved_date', models.DateTimeField(verbose_name='Received Date-Time')),
                ('purchase_id', models.CharField(blank=True, default=bakery.models.increment_purchase_number, max_length=500, null=True, verbose_name='Customer Name')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('purchase_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Purchase Total')),
            ],
            options={
                'verbose_name': 'Bakery Purchase Invoice',
                'verbose_name_plural': 'Bakery Purchase Invoice',
            },
        ),
        migrations.CreateModel(
            name='BakerySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('supplier_type', models.CharField(blank=True, choices=[('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual')], max_length=100, null=True, verbose_name='Supplier Type')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Company Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('address', models.TextField(blank=True, max_length=2550, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, default='Kumba', max_length=100, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, default='South West Region', max_length=200, null=True, verbose_name='Region')),
                ('phone1', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone 1 +237')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone 2 +237')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': ' Bakery Suppliers',
                'verbose_name_plural': 'Bakery Suppliers',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material_category_name', models.CharField(default='', max_length=100, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Raw Material Categories',
                'verbose_name_plural': 'Raw Material Categories',
            },
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material_name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Raw Material')),
                ('category', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect'), ('Semifinished Boulangerie', 'Semifinished Boulangerie'), ('Semifinished Patisserie', 'Semifinished Patisserie'), ('Finished Boulangerie', 'Finished Boulangerie'), ('Finished Patisserie', 'Finished Patisser')], default='Direct', max_length=500, null=True, verbose_name='Category')),
                ('perish_non_perish', models.CharField(blank=True, choices=[('Perishable', 'Perishable'), ('Non Perishable', 'Non Perishable')], default='Perishable', max_length=500, null=True, verbose_name='Perishable / Non Perishable')),
                ('weight_pack', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Weight/Pack')),
                ('entry_measure', models.CharField(choices=[('Grams', 'Grams'), ('Kg', 'Kg'), ('Unit', 'Unit'), ('Litre', 'Litre')], max_length=200, verbose_name='Entry Measure')),
                ('tag', models.CharField(choices=[('Raw Material', 'Raw Material'), ('Semi Finished Product', 'Semi Finished Product'), ('Finished Product', 'Finished Product')], default='', max_length=200, verbose_name='Product Tag')),
                ('packaging', models.CharField(blank=True, choices=[('Bags', 'Bags'), ('Packets', 'Packets'), ('Bottle', 'Bottle'), ('Sachets', 'Sachets'), ('Buckets', 'Buckets'), ('Litre', 'Litre'), ('Trays', 'Trays'), ('Carton', 'Carton'), ('Container', 'Container')], default='', max_length=500, null=True, verbose_name='Packaging')),
                ('raw_material_category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.rawmaterialcategory', verbose_name='Raw Material Category')),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Material',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Recipe Name')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_recipe', models.DecimalField(decimal_places=8, help_text='Quantity of raw material per recipe unit', max_digits=100)),
                ('measure', models.CharField(choices=[('Grams', 'Grams'), ('Kg', 'Kg'), ('Unit', 'Unit'), ('Litre', 'Litre')], default='', max_length=200, verbose_name='Entry Measure')),
                ('raw_material', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.rawmaterials', verbose_name='Raw Material')),
                ('recipe', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.recipe', verbose_name='Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_product', models.DecimalField(decimal_places=2, help_text='Quantity of recipe per product', max_digits=10)),
                ('product', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryproduct', verbose_name='Product Name')),
                ('recipe', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.recipe', verbose_name='Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='BakeryReturnsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakerycustomer', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryinvoice', verbose_name='Invoice Id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryproduct', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Customers Return Item',
                'verbose_name_plural': 'Customers Return Items',
            },
        ),
        migrations.CreateModel(
            name='BakeryRawMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Quantity Used')),
                ('rm_total_weight_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='RM Total Weight (KG)')),
                ('unit_cost_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Unit Cost Price')),
                ('raw_material_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Raw Material Value')),
                ('safety_stock', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Safety Stock')),
                ('avg_daily_demand', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Avg Daily Demand')),
                ('production_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryproduction')),
                ('raw_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.rawmaterials', verbose_name='Raw Material')),
            ],
            options={
                'verbose_name': 'Bakery Raw Material Usage',
                'verbose_name_plural': 'Bakery Raw Material Usage',
            },
        ),
        migrations.CreateModel(
            name='BakeryPurchaseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('purchase_id', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Purchase ID')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Purchase Value')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Amount Paid')),
                ('balance_due', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Balance Due')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('supplier_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakerysupplier', verbose_name="Supplier's Name")),
            ],
            options={
                'verbose_name': 'Bakery Purchase Summary',
                'verbose_name_plural': 'Bakery Purchase Summary',
            },
        ),
        migrations.CreateModel(
            name='BakeryPurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_installment', models.CharField(blank=True, choices=[('1st Installment', '1st Installment'), ('2nd Installment', '2nd Installment'), ('3rd Installment', '3rd Installment'), ('4th Installment', '4th Installment'), ('5th Installment', '5th Installment'), ('6th Installment', '6th Installment'), ('7th Installment', '7th Installment'), ('8th Installment', '8th Installment'), ('9th Installment', '9th Installment'), ('10th Installment', '10th Installment')], default='1st Installment', max_length=500, null=True)),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('payment_id', models.CharField(blank=True, default=bakery.models.increment_invoice_number, max_length=500, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakerycustomer', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryinvoice')),
            ],
            options={
                'verbose_name': 'Bakery Purchase Payments',
                'verbose_name_plural': 'Bakery Purchase Payments',
            },
        ),
        migrations.CreateModel(
            name='BakeryPurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=20, default=0, max_digits=200)),
                ('total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('rm_total_qty_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='RM Total Weight (KG)')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Discount value')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Discount Amount')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Net Amount')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('ordered_date', models.DateTimeField(verbose_name='Order Data-Time')),
                ('recieved_date', models.DateTimeField(verbose_name='Received Date-Time')),
                ('lead_time_days', models.DecimalField(decimal_places=20, default=0, max_digits=200)),
                ('purchase_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakerypurchase', verbose_name='Purchase Id')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_purchase', to='bakery.rawmaterials', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Bakery Purchase Item',
                'verbose_name_plural': 'Bakery Purchase Items',
            },
        ),
        migrations.AddField(
            model_name='bakerypurchase',
            name='supplier_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakerysupplier', verbose_name="Supplier's Name"),
        ),
        migrations.CreateModel(
            name='BakeryProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_category', models.CharField(blank=True, choices=[('Finished', 'Finished'), ('SemiFinished', 'SemiFinished')], default='Finished', max_length=500, null=True, verbose_name='Output Category')),
                ('mixture_number', models.CharField(blank=True, choices=[('First Mixture', 'First Mixture'), ('Second Mixture', 'Second Mixture'), ('Third Mixture', 'Third Mixture'), ('Fourth Mixture', 'Fourth Mixture'), ('Fifth Mixture', 'Fifth Mixture'), ('Sixth Mixture', 'Sixth Mixture'), ('Seventh Mixture', 'Seventh Mixture'), ('Eighth Mixture', 'Eighth Mixture'), ('Ninth Mixture', 'Ninth Mixture'), ('Tenth Mixture', 'Tenth Mixture'), ('Eleventh Mixture', 'Eleventh Mixture'), ('Twelfth Mixture', 'Twelfth Mixture'), ('Thirteenth Mixture', 'Thirteenth Mixture'), ('Fourteenth Mixture', 'Fourteenth Mixture'), ('Fifteenth Mixture', 'Fifteenth Mixture'), ('Sixteenth Mixture', 'Sixteenth Mixture'), ('Seventeenth Mixture', 'Seventeenth Mixture'), ('Eighteenth Mixture', 'Eighteenth Mixture'), ('Ninteenth Mixture', 'Nineteenth Mixture'), ('Twentieth Mixture', 'Twentieth Mixture'), ('Twenty First Mixture', 'Twenty First Mixture'), ('Twenty Second Mixture', 'Twenty Second Mixture'), ('Twenty Third Mixture', 'Twenty Third Mixture')], default='', max_length=500, null=True, verbose_name='Mixture Number')),
                ('tag', models.CharField(choices=[('Opening Stock', 'Opening Stock'), ('Production', 'Production'), ('Closing Stock', 'Closing Stock')], default='', max_length=200, verbose_name='Product Tag')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Quantity')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Price')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Output Value')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryproduct')),
                ('production_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryproduction')),
            ],
            options={
                'verbose_name': 'Bakery Production Output',
                'verbose_name_plural': 'Bakery Production Output',
            },
        ),
        migrations.CreateModel(
            name='BakeryProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100, verbose_name='Category Name')),
                ('sub_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.subdepartment', verbose_name='Sub Department')),
            ],
            options={
                'verbose_name': 'Bakery Product Category',
                'verbose_name_plural': 'Bakery Product Category',
            },
        ),
        migrations.AddField(
            model_name='bakeryproduct',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryproductcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='bakeryproduct',
            name='recipe',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.recipe', verbose_name='Recipe'),
        ),
        migrations.CreateModel(
            name='BakeryInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_id', models.CharField(blank=True, default=bakery.models.increment_invoice_number, max_length=500, null=True)),
                ('payment_installment', models.CharField(blank=True, choices=[('1st Installment', '1st Installment'), ('2nd Installment', '2nd Installment'), ('3rd Installment', '3rd Installment'), ('4th Installment', '4th Installment'), ('5th Installment', '5th Installment'), ('6th Installment', '6th Installment'), ('7th Installment', '7th Installment'), ('8th Installment', '8th Installment'), ('9th Installment', '9th Installment'), ('10th Installment', '10th Installment')], default='1st Installment', max_length=500, null=True)),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakerycustomer', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryinvoice')),
            ],
            options={
                'verbose_name': 'Bakery Customers Payments',
                'verbose_name_plural': 'Bakery Customers Payments',
            },
        ),
        migrations.CreateModel(
            name='BakeryInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('discount_price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('discount_value', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryinvoice', verbose_name='Invoice Id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryproduct', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Bakery Customer InvoicedItems',
                'verbose_name_plural': 'Bakery Customer InvoicedItems',
            },
        ),
        migrations.CreateModel(
            name='BakeryInventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], default='Morning', max_length=500, null=True)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('rm_total_qty_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='RM Total Weight (KG)')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('inventory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryinventory', verbose_name='Invoice Id')),
                ('raw_material_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.rawmaterials', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Bakery Inventory Item',
                'verbose_name_plural': 'Bakery Inventory Items',
            },
        ),
        migrations.CreateModel(
            name='BakeryCustomerOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('opening_bal_id', models.CharField(blank=True, default=bakery.models.opening_bal_increment_invoice_number, max_length=500, null=True, verbose_name='Customer Name')),
                ('description', models.CharField(blank=True, choices=[('Opening Balance', 'Opening Balance')], default='Customer Opening Balance', max_length=500, null=True, verbose_name='Description')),
                ('amount_owed', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakerycustomer', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryinvoice')),
            ],
            options={
                'verbose_name': 'Bakery Customer Opening Balance',
                'verbose_name_plural': 'Bakery Customer Opening Balance',
            },
        ),
        migrations.CreateModel(
            name='BakeryConsumptionDamages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Consumption', 'Consumption'), ('Damages', 'Damages')], default='', max_length=500, null=True, verbose_name='Status')),
                ('session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Session')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Employee')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Quantity')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Price')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Output Value')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryproduct')),
                ('production_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakeryproduction')),
                ('sub_department', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.subdepartment', verbose_name='Sub Department')),
            ],
            options={
                'verbose_name': 'Bakery Consumption & Damages',
                'verbose_name_plural': 'Bakery Consumption & Damages',
            },
        ),
    ]
