# Generated by Django 4.2.7 on 2024-10-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryrawmaterialusage',
            name='status',
            field=models.CharField(blank=True, choices=[('Direct Usage', 'Direct Usage'), ('Indirect Usage', 'Indirect Usage')], default='', max_length=500, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bakerypurchaseitems',
            name='lead_time_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='bakerypurchaseitems',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='bakerypurchaseitems',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
