# Generated by Django 4.2.7 on 2024-11-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_bakeryrawmaterialusage_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryProductUnitWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_per_boul', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('output_per_boul', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('product_unit_weight', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.bakeryproduct')),
            ],
            options={
                'verbose_name': 'Bakery Product Unit Weight',
                'verbose_name_plural': 'Bakery Product Unit Weights',
            },
        ),
    ]
