# Generated by Django 4.2.7 on 2024-11-19 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_bakeryproductunitweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryconsumptiondamages',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
