# Generated by Django 4.2.7 on 2024-11-21 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_bakeryconsumptiondamages_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryrawmaterialusage',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
