# Generated by Django 4.2.7 on 2024-11-21 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_bakeryrawmaterialusage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryproductionoutput',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
