# Generated by Django 4.2.7 on 2025-11-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_bakeryproductionoutput_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrecipe',
            options={'verbose_name': 'Product Recipe', 'verbose_name_plural': 'Product Recipes'},
        ),
        migrations.AlterField(
            model_name='reciperawmaterial',
            name='measure',
            field=models.CharField(choices=[('Grams', 'Grams'), ('Kg', 'Kg'), ('Unit', 'Unit'), ('Litre', 'Litre'), ('Ml', 'Ml')], default='', max_length=200, verbose_name='Entry Measure'),
        ),
    ]
