# Generated by Django 4.2.7 on 2024-09-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_author_user_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='instruction2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='instruction3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='instruction4',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='instruction5',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
