# Generated by Django 4.1 on 2022-10-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, max_length=2550, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, default='Kumba', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='region',
            field=models.CharField(blank=True, default='South West Region', max_length=200, null=True, verbose_name='Region'),
        ),
    ]
