# Generated by Django 4.2.7 on 2024-09-20 17:28

import bar.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('inventory_id', models.CharField(blank=True, default=bar.models.increment_inventory_number, max_length=500, null=True, verbose_name='Inventory Id')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Stock Person')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=20, null=True, verbose_name='Total Price')),
            ],
            options={
                'verbose_name': 'Bar Inventory',
                'verbose_name_plural': 'Bar Inventory',
            },
        ),
        migrations.CreateModel(
            name='BarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100, unique=True, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Supply Price')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Selling Price')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('unit_measure', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Litres/grams')),
            ],
            options={
                'verbose_name': 'Bar Product',
                'verbose_name_plural': 'Bar Products',
            },
        ),
        migrations.CreateModel(
            name='BarProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Bar Product Category',
                'verbose_name_plural': 'Bar Product Category',
            },
        ),
        migrations.CreateModel(
            name='BarPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('purchase_id', models.CharField(blank=True, default=bar.models.increment_purchase_number, max_length=500, null=True, verbose_name='Customer Name')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie Morning', 'Boulangerie Morning'), ('Boulangerie Evening', 'Boulangerie Evening'), ('Patisserie', 'Patisserie'), ('Magazine', 'Magazine')], default='Morning', max_length=500, null=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('purchase_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Purchase Total')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='VAT Amount')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Discount Amount')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Net Amount')),
                ('status', models.CharField(blank=True, choices=[('Purchases', 'Purchases'), ('Return Outwards', 'Return Outwards')], default='Purchases', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Bar Purchase Invoice',
                'verbose_name_plural': 'Bar Purchase Invoice',
            },
        ),
        migrations.CreateModel(
            name='BarSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('supplier_type', models.CharField(blank=True, choices=[('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual')], max_length=100, null=True, verbose_name='Supplier Type')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Company Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('address', models.TextField(blank=True, max_length=2550, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, default='Kumba', max_length=100, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, default='South West Region', max_length=200, null=True, verbose_name='Region')),
                ('phone1', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone 1 +237')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone 2 +237')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': ' Bar Suppliers',
                'verbose_name_plural': 'Bar Suppliers',
            },
        ),
        migrations.CreateModel(
            name='BarPurchaseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('purchase_id', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Purchase ID')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Purchase Value')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Amount Paid')),
                ('balance_due', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Balance Due')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('supplier_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.barsupplier', verbose_name="Supplier's Name")),
            ],
            options={
                'verbose_name': 'Bar Purchase Summary',
                'verbose_name_plural': 'Bar Purchase Summary',
            },
        ),
        migrations.CreateModel(
            name='BarPurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_installment', models.CharField(blank=True, choices=[('1st Installment', '1st Installment'), ('2nd Installment', '2nd Installment'), ('3rd Installment', '3rd Installment'), ('4th Installment', '4th Installment'), ('5th Installment', '5th Installment'), ('6th Installment', '6th Installment'), ('7th Installment', '7th Installment'), ('8th Installment', '8th Installment'), ('9th Installment', '9th Installment'), ('10th Installment', '10th Installment')], default='1st Installment', max_length=500, null=True)),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.barsupplier', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.barpurchase')),
            ],
            options={
                'verbose_name': 'Boulangerie Customers Payments',
                'verbose_name_plural': 'Boulangerie Customers Payments',
            },
        ),
        migrations.CreateModel(
            name='BarPurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Quantity')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Selling Price')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Discount value')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Discount Amount')),
                ('total_cost_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Total Cost Price')),
                ('total_selling_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Total Selling Price')),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Gross Profit')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.barproduct', verbose_name='Product Name')),
                ('purchase_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.barpurchase', verbose_name='Purchase ID')),
            ],
            options={
                'verbose_name': 'Bar Purchase Item',
                'verbose_name_plural': 'Bar Purchase Items',
            },
        ),
        migrations.AddField(
            model_name='barpurchase',
            name='supplier_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.barsupplier', verbose_name="Supplier's Name"),
        ),
        migrations.AddField(
            model_name='barproduct',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.barproductcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='BarInventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Added Stock', 'Added Stock'), ('Closing Stock', 'Closing Stock'), ('Damages', 'Damages'), ('Returns Outwards', 'Returns Outwards'), ('Returns Inwards', 'Returns Inwards')], default='Morning', max_length=500, null=True)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Selling Price')),
                ('total_cost_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Total Cost Price')),
                ('total_selling_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Total Selling Price')),
                ('inventory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.barinventory', verbose_name='Inventory Id')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.barproduct', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Bar Inventory Item',
                'verbose_name_plural': 'Bar Inventory Items',
            },
        ),
    ]
