# Generated by Django 4.2.7 on 2024-09-16 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import invoice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('inventory', '0001_initial'),
        ('supplier', '0002_alter_supplier_address_alter_supplier_city_and_more'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('invoice_id', models.CharField(blank=True, default=invoice.models.bakery_increment_invoice_number, max_length=500, null=True, verbose_name='Invoice Id')),
                ('sales_session', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Invoice Total')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('apply_vat', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer', verbose_name='Customer Name')),
            ],
            options={
                'verbose_name': 'Customers Invoice',
                'verbose_name_plural': 'Customers Invoices',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('purchase_id', models.CharField(blank=True, default=invoice.models.increment_purchase_number, max_length=500, null=True, verbose_name='Customer Name')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='employee')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie Morning', 'Boulangerie Morning'), ('Boulangerie Evening', 'Boulangerie Evening'), ('Patisserie', 'Patisserie'), ('Magazine', 'Magazine')], default='Morning', max_length=500, null=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('purchase_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Purchase Total')),
                ('supplier_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier', verbose_name="Supplier's Name")),
            ],
            options={
                'verbose_name': 'Purchase Invoice',
                'verbose_name_plural': 'Purchase Invoice',
            },
        ),
        migrations.CreateModel(
            name='ReturnsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice', verbose_name='Invoice Id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Customers Return Item',
                'verbose_name_plural': 'Customers Return Items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('purchase_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.purchase', verbose_name='Purchase Id')),
                ('raw_material_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_purchase', to='inventory.rawmaterials', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_installment', models.CharField(blank=True, choices=[('1st Installment', '1st Installment'), ('2nd Installment', '2nd Installment'), ('3rd Installment', '3rd Installment'), ('4th Installment', '4th Installment'), ('5th Installment', '5th Installment'), ('6th Installment', '6th Installment'), ('7th Installment', '7th Installment'), ('8th Installment', '8th Installment'), ('9th Installment', '9th Installment'), ('10th Installment', '10th Installment')], default='1st Installment', max_length=500, null=True)),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer', verbose_name='Customer Name')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'Customers Payments',
                'verbose_name_plural': 'Customers Payments',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(choices=[('Moses', 'Moses'), ('Nelson', 'Nelson')], default='', max_length=200, verbose_name='Sale Person')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('discount_price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('discount_value', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice', verbose_name='Invoice Id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Customers Invoice Items',
                'verbose_name_plural': 'Customers Invoice Items',
            },
        ),
    ]
