"""
Django settings for bernard_john_erp_v1 project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g*owtue*&en@qt%-u3_6&mi0nmej5s$mtzv#(9vqoj7__j#tqx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom Apps
    'configuration.apps.ConfigurationConfig',
    'bakery.apps.BakeryConfig',
    'accounting.apps.AccountingConfig',
    'supermarket.apps.SupermarketConfig',
    'bar.apps.BarConfig',
    'boulangerie.apps.BoulangerieConfig',
    'wholesale.apps.WholesaleConfig',
    'customer.apps.CustomerConfig',
    'supplier.apps.SupplierConfig',
    'invoice.apps.InvoiceConfig',
    'product.apps.ProductConfig',
    'inventory.apps.InventoryConfig',
    'purchases.apps.PurchasesConfig',
    'task.apps.TaskConfig',
    'production.apps.ProductionConfig',
    

    # Third Party Apps
    'import_export',
    "django_browser_reload",
    'widget_tweaks',
    'django_selectize',
    
    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    'user.middleware.LoginRequiredMiddleware',  # Add your custom middleware here

]

ROOT_URLCONF = 'bernard_john_erp_v1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'user/templates'),
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bernard_john_erp_v1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'), # database name
        'USER': os.getenv('DB_USER'), #username
        'PASSWORD': os.getenv('DB_PASSWORD'), #password
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    },

}

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': 'debug.log',
#         },
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file', 'console'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Africa/Douala"

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True
USE_THOUSAND_SEPARATOR=True

THOUSAND_SEPARATOR=','

DECIMAL_SEPARATOR='.'

NUMBER_GROUPING=3

DATE_INPUT_FORMATS = ('%m/%d/%Y',)
USE_I18N = True
USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/



STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',      # This is where you store your global static files
    BASE_DIR / 'app-assets',  # Another directory for your static files
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#############   #############   #############   #############   #############
    #------------------------- JAZZMIN SETTINGS --------------------------------#
    #############   #############   #############   #############   #############
JAZZMIN_SETTINGS = {
    "site_title": "BJ COMPLEX",
    "site_header": "BJ COMPLEX",
    "site_brand": "BJ COMPLEX",
    "site_icon": "images/favicon.png",
    # Add your own branding here
    "site_logo": None,
    "welcome_sign": "Welcome to BJ COMPLEX LTD",
    # Copyright on the footer
    "copyright": "BJ COMPLEX",
    "user_avatar": None,

    "search_model": ["auth.User", "auth.Group", ],
    ############
    # Top Menu #
    ############
    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "BJ COMPLEX", "url": "home", "permissions": ["auth.view_user"]},
        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},
    ],

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": ['returns'],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    #############
    # Side Menu #
    #############
    # Whether to display the side menu
    "show_sidebar": True,
    # Whether to aut expand the menu
    "navigation_expanded": True,
    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        

        "users.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "admin.LogEntry": "fas fa-file",


        # Configs_settings
        "configuration.Region": "fas fa-globe-europe",
        "configuration.Country": "fas fa-flag",
        "configuration.Session": "fas fa-hourglass-end",
        "configuration.ManagementLevel": "fas fa-sitemap",
        "configuration.WorkLocation": "fas fa-building",
        "configuration.Department": "fas fa-laptop-house",
        "configuration.SubDepartment": "fas fa-network-wired",
        "configuration.JobPosition": "fas fa-user-tie",

        # Customers
        "bakery.BakeryCustomer": "fas fa-users",
        "bakery.BakeryProduct": "fas fa-cubes",
        "bakery.BakeryProductCategory": "fas fa-boxes",
        "bakery.BakeryInvoice": "fas fa-receipt",
        "bakery.BakeryInvoiceDetail": "fas fa-shopping-cart",
        "bakery.BakeryInvoicePayment": "fas fa-money-bill-wave",
        "bakery.BakerySupplier": "fas fa-users",
        "bakery.BakeryPurchaseSummary": "fas fa-clipboard",
        "bakery.RawMaterials": "fas fa-industry",
        "bakery.BakeryPurchase": "fas fa-receipt",
        "bakery.BakeryPurchaseItems": "fas fa-dolly",
        "bakery.BakeryInventory": "fas fa-dolly-flatbed",
        "bakery.BakeryInventoryItems": "fas fa-pallet",

         "bakery.BakeryCustomerOperningBalance": "fas fa-credit-card",

        "bakery.BakeryProduction": "fas fa-industry",
        "bakery.BakeryRawMaterialUsage": "fas fa-dolly-flatbed",
        "bakery.BakeryProductionOutput": "fas fa-truck",
        "bakery.BakeryConsumptionDamages": "fas fa-bug",


        # Accounting
        "accounting.BakeryGeneralLedger": "fas fa-book",
        "accounting.SupermarketGeneralLedger": "fas fa-book",
        "accounting.BoulangerieGeneralLedger": "fas fa-book",
        "accounting.BarGeneralLedger": "fas fa-book",
        
        "accounting.AccountsCategory": "fas fa-book",
        "accounting.AccountsSubCategory": "fas fa-book",
        "accounting.AccountsDebit": "fas fa-address-book",
        "accounting.AccountsCredit": "fas fa-address-book",


        # Human Resource
        "human_resource.Employee": "fas fa-users",

        # Supermarket
        "supermarket.SupermarketProductCategory": "fas fa-boxes",
        "supermarket.SupermarketProductSubCategory": "fas fa-boxes",
        "supermarket.SupermarketProduct": "fas fa-cubes",
        "supermarket.SupermarketCustomer": "fas fa-users",
        "supermarket.SupermarketInvoice": "fas fa-receipt",
        "supermarket.SupermarketInvoiceDetail": "fas fa-shopping-cart",

           # Wholesale
        "wholesale.WholesaleProductCategory": "fas fa-boxes",
        "wholesale.WholesaleProductSubCategory": "fas fa-boxes",
        "wholesale.WholesaleProduct": "fas fa-cubes",
        "wholesale.WholesaleCustomer": "fas fa-users",
        "wholesale.WholesaleInvoice": "fas fa-receipt",
        "wholesale.WholesaleInvoiceDetail": "fas fa-shopping-cart",
        
        # Purchases
        "purchase.Vendor": "fas fa-users",
        "purchase.PurchaseInvoices": "fas fa-receipt",
        "purchase.PurchaseInvoicesDetail": "fas fa-shopping-basket",

        # Inventory Management
        "inventory_management.Inventory": "fas fa-boxes",
        "inventory_management.InventoryItems": "fas fa-pallet",

        # Product
        "product.Product": "fas fa-cubes",
        "product.ProductCategory": "fas fa-layer-group",

        # Storage
        "storage_location.Storage": "fas fa-warehouse",

        # Transfers
        "transfers.TransferInvoice": "fas fa-truck",
        "transfers.TransferDetail": "fas fa-file-alt",
    },
    # # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-arrow-circle-right",
    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,
    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    # Uncomment this line once you create the bootstrap-dark.css file
    # "custom_css": "css/bootstrap-dark.css",
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,
    ###############
    # Change view #
    ###############
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",

         "customers.Customer": "horizontal_tabs",
    },

    # Add a language dropdown into the admin
    "language_chooser": False,
}

    #############   #############   #############   #############   #############
    #------------------------- JAZZMIN UI TWEAKS SETTINGS --------------------------------#
    #############   #############   #############   #############   #############

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-teal",
    "accent": "accent-navy",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-teal",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-outline-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}