# Generated by Django 4.2.7 on 2024-09-16 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_category', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Accounts Debit')),
            ],
            options={
                'verbose_name': 'Accounts Category',
                'verbose_name_plural': 'Accounts Categories',
            },
        ),
        migrations.CreateModel(
            name='AccountsCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_credit', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Accounts Credit')),
            ],
            options={
                'verbose_name': 'Accounts Credit',
                'verbose_name_plural': 'Accounts Credit',
            },
        ),
        migrations.CreateModel(
            name='AccountsDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_debit', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Accounts Debit')),
            ],
            options={
                'verbose_name': 'Accounts Debit',
                'verbose_name_plural': 'Accounts Debit',
            },
        ),
        migrations.CreateModel(
            name='WholesaleGeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('employee_name', models.CharField(blank=True, default='', help_text='Name of Employee Performing the Transaction', max_length=500, null=True, verbose_name='Employee Name')),
                ('custom_user', models.CharField(blank=True, default='', help_text='Person Entering the Data', max_length=500, null=True, verbose_name='User')),
                ('institution', models.CharField(blank=True, default='', help_text='Name of Supplier, Bank, Contractor etc', max_length=500, null=True, verbose_name='Institution')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Amount')),
                ('accounts_credit', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountscredit', verbose_name='Accounts Credit')),
                ('accounts_debit', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountsdebit', verbose_name='Accounts Debit')),
                ('department_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.department', verbose_name='Department')),
                ('management_level', models.ForeignKey(blank=True, help_text='Management or Employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.managementlevel', verbose_name='Management Level')),
            ],
            options={
                'verbose_name': 'Wholesale General Ledger',
                'verbose_name_plural': 'Wholesale General Ledger',
            },
        ),
        migrations.CreateModel(
            name='SupermarketGeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('employee_name', models.CharField(blank=True, default='', help_text='Name of Employee Performing the Transaction', max_length=500, null=True, verbose_name='Employee Name')),
                ('custom_user', models.CharField(blank=True, default='', help_text='Person Entering the Data', max_length=500, null=True, verbose_name='User')),
                ('institution', models.CharField(blank=True, default='', help_text='Name of Supplier, Bank, Contractor etc', max_length=500, null=True, verbose_name='Institution')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Amount')),
                ('accounts_credit', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountscredit', verbose_name='Accounts Credit')),
                ('accounts_debit', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountsdebit', verbose_name='Accounts Debit')),
                ('department_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.department', verbose_name='Department')),
                ('management_level', models.ForeignKey(blank=True, help_text='Management or Employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.managementlevel', verbose_name='Management Level')),
            ],
            options={
                'verbose_name': 'Supermarket General Ledger',
                'verbose_name_plural': 'Supermarket General Ledger',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieGeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('employee_name', models.CharField(blank=True, default='', help_text='Name of Employee Performing the Transaction', max_length=500, null=True, verbose_name='Employee Name')),
                ('custom_user', models.CharField(blank=True, default='', help_text='Person Entering the Data', max_length=500, null=True, verbose_name='User')),
                ('institution', models.CharField(blank=True, default='', help_text='Name of Supplier, Bank, Contractor etc', max_length=500, null=True, verbose_name='Institution')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Amount')),
                ('accounts_credit', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountscredit', verbose_name='Accounts Credit')),
                ('accounts_debit', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountsdebit', verbose_name='Accounts Debit')),
                ('department_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.department', verbose_name='Department')),
                ('management_level', models.ForeignKey(blank=True, help_text='Management or Employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.managementlevel', verbose_name='Management Level')),
            ],
            options={
                'verbose_name': 'Boulangerie General Ledger',
                'verbose_name_plural': 'Boulangerie General Ledger',
            },
        ),
        migrations.CreateModel(
            name='BarGeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('employee_name', models.CharField(blank=True, default='', help_text='Name of Employee Performing the Transaction', max_length=500, null=True, verbose_name='Employee Name')),
                ('custom_user', models.CharField(blank=True, default='', help_text='Person Entering the Data', max_length=500, null=True, verbose_name='User')),
                ('institution', models.CharField(blank=True, default='', help_text='Name of Supplier, Bank, Contractor etc', max_length=500, null=True, verbose_name='Institution')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Amount')),
                ('accounts_credit', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountscredit', verbose_name='Accounts Credit')),
                ('accounts_debit', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountsdebit', verbose_name='Accounts Debit')),
                ('department_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.department', verbose_name='Department')),
                ('management_level', models.ForeignKey(blank=True, help_text='Management or Employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.managementlevel', verbose_name='Management Level')),
            ],
            options={
                'verbose_name': 'Bar General Ledger',
                'verbose_name_plural': 'Bar General Ledger',
            },
        ),
        migrations.CreateModel(
            name='BakeryGeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('employee_name', models.CharField(blank=True, default='', help_text='Name of Employee Performing the Transaction', max_length=500, null=True, verbose_name='Employee Name')),
                ('custom_user', models.CharField(blank=True, default='', help_text='Person Entering the Data', max_length=500, null=True, verbose_name='User')),
                ('institution', models.CharField(blank=True, default='', help_text='Name of Supplier, Bank, Contractor etc', max_length=500, null=True, verbose_name='Institution')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Amount')),
                ('accounts_credit', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountscredit', verbose_name='Accounts Credit')),
                ('accounts_debit', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountsdebit', verbose_name='Accounts Debit')),
                ('department_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.department', verbose_name='Department')),
                ('management_level', models.ForeignKey(blank=True, help_text='Management or Employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.managementlevel', verbose_name='Management Level')),
            ],
            options={
                'verbose_name': 'Bakery General Ledger',
                'verbose_name_plural': 'Bakery General Ledger',
            },
        ),
        migrations.CreateModel(
            name='AccountsSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sub_category', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Accounts Sub Category')),
                ('accounts_category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountscategory', verbose_name='Accounts Category')),
            ],
            options={
                'verbose_name': 'Accounts Sub Category',
                'verbose_name_plural': 'Accounts Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='accountsdebit',
            name='accounts_sub_category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountssubcategory', verbose_name='Accounts Sub Category'),
        ),
        migrations.AddField(
            model_name='accountscredit',
            name='accounts_sub_category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountssubcategory', verbose_name='Accounts Sub Category'),
        ),
    ]
